param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"

function From-CodePoint {
    param([int[]]$CodePoints)
    return (($CodePoints | ForEach-Object { [char]$_ }) -join "")
}

$tempFolder = Join-Path $Root ("00 " + (From-CodePoint @(0x4E34, 0x65F6, 0x7BB1)))
$wikiFolder = Join-Path $Root "wiki"
$sourceFolder = Join-Path $wikiFolder (From-CodePoint @(0x6765, 0x6E90))
$projectsFolder = Join-Path $Root "projects"
$queueName = (From-CodePoint @(0x0030, 0x0030, 0x4E34, 0x65F6, 0x7BB1, 0x81EA, 0x52A8, 0x5DE1, 0x68C0, 0x961F, 0x5217)) + ".md"
$stateName = (From-CodePoint @(0x0030, 0x0030, 0x4E34, 0x65F6, 0x7BB1, 0x81EA, 0x52A8, 0x5DE1, 0x68C0, 0x72B6, 0x6001)) + ".json"
$queuePath = Join-Path $projectsFolder $queueName
$statePath = Join-Path $projectsFolder $stateName

if (-not (Test-Path -LiteralPath $tempFolder)) {
    throw "Temp folder not found: $tempFolder"
}

$sourcePages = @()
if (Test-Path -LiteralPath $sourceFolder) {
    $sourcePages = Get-ChildItem -LiteralPath $sourceFolder -File -Filter "*.md"
}

function Get-FrontmatterValue {
    param(
        [string]$Text,
        [string]$Key
    )

    $match = [regex]::Match($Text, "(?m)^$([regex]::Escape($Key)):\s*(.+)$")
    if ($match.Success) {
        return $match.Groups[2].Value.Trim()
    }

    return ""
}

function Test-SourcePageExists {
    param(
        [System.IO.FileInfo]$File,
        [string]$Url
    )

    foreach ($page in $sourcePages) {
        $pageText = Get-Content -LiteralPath $page.FullName -Raw -Encoding UTF8
        if ($page.BaseName -eq $File.BaseName) {
            return $true
        }

        if ($pageText -match [regex]::Escape($File.BaseName)) {
            return $true
        }

        if ($Url -and $pageText -match [regex]::Escape($Url)) {
            return $true
        }
    }

    return $false
}

function Get-Classification {
    param(
        [System.IO.FileInfo]$File,
        [string]$Text,
        [bool]$SourcePageExists
    )

    $body = [regex]::Replace($Text, "(?s)^---.*?---", "").Trim()
    $metaHint = (From-CodePoint @(0x521D, 0x6B65, 0x63D0, 0x70BC))
    $syncHint = (From-CodePoint @(0x540C, 0x6B65, 0x52A9, 0x624B))

    if (($File.BaseName -match $metaHint) -or ($File.BaseName -match $syncHint)) {
        return "META"
    }

    if ($SourcePageExists) {
        return "READY_TO_ARCHIVE"
    }

    if (
        ($File.Length -lt 1500) -and
        ($body -notmatch "^#|source:|author:|url:|saved:|tags:")
    ) {
        return "EMPTY_OR_JUMP"
    }

    return "PENDING_INGEST"
}

$items = @()
$files = Get-ChildItem -LiteralPath $tempFolder -File -Filter "*.md" | Sort-Object Name
foreach ($file in $files) {
    $text = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $url = Get-FrontmatterValue -Text $text -Key "url"
    $hasSourcePage = Test-SourcePageExists -File $file -Url $url
    $classification = Get-Classification -File $file -Text $text -SourcePageExists $hasSourcePage

    $items += [pscustomobject]@{
        Classification = $classification
        File = $file.Name
        Bytes = $file.Length
        LastWriteTime = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
    }
}

$counts = $items | Group-Object Classification | Sort-Object Name
$generatedAt = Get-Date
$lines = New-Object 'System.Collections.Generic.List[string]'

$lines.Add("---")
$lines.Add("generated: $($generatedAt.ToString('yyyy-MM-dd HH:mm:ss'))")
$lines.Add("status: pending")
$lines.Add("automation: scan-only")
$lines.Add("---")
$lines.Add("")
$lines.Add("# Temp box scan queue")
$lines.Add("")
$lines.Add("> Generated by scan_obsidian_temp_box.ps1.")
$lines.Add("> This scan does not modify source notes or stable wiki pages.")
$lines.Add("")
$lines.Add("## Counts")
$lines.Add("")

foreach ($count in $counts) {
    $lines.Add("- $($count.Name): $($count.Count)")
}

foreach ($classification in @("PENDING_INGEST", "READY_TO_ARCHIVE", "EMPTY_OR_JUMP", "META")) {
    $group = @($items | Where-Object { $_.Classification -eq $classification })
    if ($group.Count -eq 0) {
        continue
    }

    $lines.Add("")
    $lines.Add("## $classification")
    $lines.Add("")

    foreach ($item in $group) {
        $lines.Add("- $($item.File) ($($item.Bytes) bytes; $($item.LastWriteTime))")
    }
}

$lines.Add("")
$lines.Add("## Next action")
$lines.Add("")
$lines.Add("- PENDING_INGEST: review and ingest with Codex.")
$lines.Add("- EMPTY_OR_JUMP: keep as a marker; do not infer missing content.")
$lines.Add("- META: keep as a process record or temporary synthesis.")
$lines.Add("- READY_TO_ARCHIVE: source page exists; archive only after confirmation.")

Set-Content -LiteralPath $queuePath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8

$countMap = @{}
foreach ($count in $counts) {
    $countMap[$count.Name] = $count.Count
}

$state = [pscustomobject]@{
    GeneratedAt = $generatedAt.ToString("o")
    Root = $Root
    FileCount = $items.Count
    Counts = $countMap
}

$state | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $statePath -Encoding UTF8

Write-Output "queue=$queuePath"
Write-Output "state=$statePath"
Write-Output "files=$($items.Count)"
foreach ($count in $counts) {
    Write-Output "$($count.Name)=$($count.Count)"
}
